local icons = require("nvim-nonicons.mapping")
local devicons = require("nvim-web-devicons")

local function get(name)
  return vim.fn.nr2char(icons[name]) .. ' '
end

devicons.set_icon({
  [".babelrc"] = {
    icon = get("json"),
    color = "#cbcb41",
    cterm_color = "185",
    name = "Babelrc",
  },
  [".bashprofile"] = {
    icon = get("gear"),
    color = "#89e051",
    cterm_color = "113",
    name = "BashProfile",
  },
  [".bashrc"] = {
    icon = get("gear"),
    color = "#89e051",
    cterm_color = "113",
    name = "Bashrc",
  },
  [".ds_store"] = {
    icon = get("gear"),
    color = "#41535b",
    cterm_color = "59",
    name = "DsStore",
  },
  [".gitattributes"] = {
    icon = get("git-commit"),
    color = "#41535b",
    cterm_color = "59",
    name = "GitAttributes",
  },
  [".gitconfig"] = {
    icon = get("gear"),
    color = "#41535b",
    cterm_color = "59",
    name = "GitConfig",
  },
  [".gitignore"] = {
    icon = get("git-commit"),
    color = "#41535b",
    cterm_color = "59",
    name = "GitIgnore",
  },
  [".gitlab-ci.yml"] = {
    icon = get("yarn"),
    color = "#e24329",
    cterm_color = "166",
    name = "GitlabCI",
  },
  [".gitmodules"] = {
    icon = get("git-commit"),
    color = "#41535b",
    cterm_color = "59",
    name = "GitModules",
  },
  [".gvimrc"] = {
    icon = get("vim"),
    color = "#019833",
    cterm_color = "29",
    name = "Gvimrc",
  },
  [".npmignore"] = {
    icon = get("npm"),
    color = "#E8274B",
    cterm_color = "161",
    name = "NPMIgnore",
  },
  [".settings.json"] = {
    icon = get("vscode"),
    color = "#854CC7",
    cterm_color = "98",
    name = "SettingsJson",
  },
  [".vimrc"] = {
    icon = get("vim"),
    color = "#019833",
    cterm_color = "29",
    name = "Vimrc",
  },
  [".zprofile"] = {
    icon = get("gear"),
    color = "#89e051",
    cterm_color = "113",
    name = "Zshprofile",
  },
  [".zshenv"] = {
    icon = get("gear"),
    color = "#89e051",
    cterm_color = "113",
    name = "Zshenv",
  },
  [".zshrc"] = {
    icon = get("gear"),
    color = "#89e051",
    cterm_color = "113",
    name = "Zshrc",
  },
  ["Brewfile"] = {
    icon = get("ruby"),
    color = "#701516",
    cterm_color = "52",
    name = "Brewfile",
  },
  ["CMakeLists.txt"] = {
    icon = get("gear"),
    color = "#6d8086",
    cterm_color = "66",
    name = "CMakeLists",
  },
  ["COMMIT_EDITMSG"] = {
    icon = get("git-commit"),
    color = "#41535b",
    cterm_color = "59",
    name = "GitCommit",
  },
  ["COPYING"] = {
    icon = get("file-badge"),
    color = "#cbcb41",
    cterm_color = "185",
    name = "License",
  },
  ["COPYING.LESSER"] = {
    icon = get("file-badge"),
    color = "#cbcb41",
    cterm_color = "185",
    name = "License",
  },
  ["Dockerfile"] = {
    icon = get("docker"),
    color = "#384d54",
    cterm_color = "59",
    name = "Dockerfile",
  },
  ["Gemfile$"] = {
    icon = get("ruby"),
    color = "#701516",
    cterm_color = "52",
    name = "Gemfile",
  },
  ["LICENSE"] = {
    icon = get("file-badge"),
    color = "#d0bf41",
    cterm_color = "179",
    name = "License",
  },
  ["R"] = {
    icon = get("r"),
    color = "#358a5b",
    cterm_color = "65",
    name = "R",
  },
  ["Rmd"] = {
    icon = get("markdown"),
    color = "#519aba",
    cterm_color = "67",
    name = "Rmd",
  },
  ["Vagrantfile$"] = {
    icon = get("ruby"),
    color = "#1563FF",
    cterm_color = "27",
    name = "Vagrantfile",
  },
  ["_gvimrc"] = {
    icon = get("vim"),
    color = "#019833",
    cterm_color = "29",
    name = "Gvimrc",
  },
  ["_vimrc"] = {
    icon = get("vim"),
    color = "#019833",
    cterm_color = "29",
    name = "Vimrc",
  },
  ["ai"] = {
    icon = get("image"),
    color = "#cbcb41",
    cterm_color = "185",
    name = "Ai",
  },
  ["awk"] = {
    icon = get("terminal"),
    color = "#4d5a5e",
    cterm_color = "59",
    name = "Awk",
  },
  ["bash"] = {
    icon = get("terminal"),
    color = "#89e051",
    cterm_color = "113",
    name = "Bash",
  },
  ["bat"] = {
    icon = get("gear"),
    color = "#C1F12E",
    cterm_color = "154",
    name = "Bat",
  },
  ["bmp"] = {
    icon = get("image"),
    color = "#a074c4",
    cterm_color = "140",
    name = "Bmp",
  },
  ["c"] = {
    icon = get("c"),
    color = "#599eff",
    cterm_color = "75",
    name = "C",
  },
  ["c++"] = {
    icon = get("c-plusplus"),
    color = "#f34b7d",
    cterm_color = "204",
    name = "CPlusPlus",
  },
  ["cbl"] = {
    icon = get("gear"),
    color = "#005ca5",
    cterm_color = "25",
    name = "Cobol",
  },
  ["cc"] = {
    icon = get("c-plusplus"),
    color = "#f34b7d",
    cterm_color = "204",
    name = "CPlusPlus",
  },
  ["cfg"] = {
    icon = get("file-code"),
    color = "#ECECEC",
    cterm_color = "231",
    name = "Configuration",
  },
  ["clj"] = {
    icon = get("file-code"),
    color = "#8dc149",
    cterm_color = "107",
    name = "Clojure",
  },
  ["cljc"] = {
    icon = get("file-code"),
    color = "#8dc149",
    cterm_color = "107",
    name = "ClojureC",
  },
  ["cljs"] = {
    icon = get("file-code"),
    color = "#519aba",
    cterm_color = "67",
    name = "ClojureJS",
  },
  ["cmake"] = {
    icon = get("gear"),
    color = "#6d8086",
    cterm_color = "66",
    name = "CMake",
  },
  ["cob"] = {
    icon = get("gear"),
    color = "#005ca5",
    cterm_color = "25",
    name = "Cobol",
  },
  ["cobol"] = {
    icon = get("gear"),
    color = "#005ca5",
    cterm_color = "25",
    name = "Cobol",
  },
  ["coffee"] = {
    icon = get("java"),
    color = "#cbcb41",
    cterm_color = "185",
    name = "Coffee",
  },
  ["conf"] = {
    icon = get("gear"),
    color = "#6d8086",
    cterm_color = "66",
    name = "Conf",
  },
  ["config.ru"] = {
    icon = get("ruby"),
    color = "#701516",
    cterm_color = "52",
    name = "ConfigRu",
  },
  ["cp"] = {
    icon = get("c-plusplus"),
    color = "#519aba",
    cterm_color = "67",
    name = "Cp",
  },
  ["cpp"] = {
    icon = get("c-plusplus"),
    color = "#519aba",
    cterm_color = "67",
    name = "Cpp",
  },
  ["cpy"] = {
    icon = get("gear"),
    color = "#005ca5",
    cterm_color = "25",
    name = "Cobol",
  },
  ["cr"] = {
    icon = get("file-code"),
    color = "#000000",
    cterm_color = "16",
    name = "Crystal",
  },
  ["cs"] = {
    icon = get("c-sharp"),
    color = "#596706",
    cterm_color = "58",
    name = "Cs",
  },
  ["csh"] = {
    icon = get("terminal"),
    color = "#4d5a5e",
    cterm_color = "59",
    name = "Csh",
  },
  ["cson"] = {
    icon = get("json"),
    color = "#cbcb41",
    cterm_color = "185",
    name = "Cson",
  },
  ["css"] = {
    icon = get("css"),
    color = "#563d7c",
    cterm_color = "60",
    name = "Css",
  },
  ["csv"] = {
    icon = get("file"),
    color = "#89e051",
    cterm_color = "113",
    name = "Csv",
  },
  ["cxx"] = {
    icon = get("c-plusplus"),
    color = "#519aba",
    cterm_color = "67",
    name = "Cxx",
  },
  ["d"] = {
    icon = get("file-code"),
    color = "#427819",
    cterm_color = "64",
    name = "D",
  },
  ["dart"] = {
    icon = get("file-code"),
    color = "#03589C",
    cterm_color = "25",
    name = "Dart",
  },
  ["db"] = {
    icon = get("database"),
    color = "#dad8d8",
    cterm_color = "188",
    name = "Db",
  },
  ["desktop"] = {
    icon = get("arrow-switch"),
    color = "#563d7c",
    cterm_color = "60",
    name = "DesktopEntry",
  },
  ["diff"] = {
    icon = get("file-diff"),
    color = "#41535b",
    cterm_color = "59",
    name = "Diff",
  },
  ["doc"] = {
    icon = get("file"),
    color = "#185abd",
    cterm_color = "25",
    name = "Doc",
  },
  ["dockerfile"] = {
    icon = get("docker"),
    color = "#384d54",
    cterm_color = "59",
    name = "Dockerfile",
  },
  ["dropbox"] = {
    icon = get("package"),
    color = "#0061FE",
    cterm_color = "27",
    name = "Dropbox",
  },
  ["dump"] = {
    icon = get("database"),
    color = "#dad8d8",
    cterm_color = "188",
    name = "Dump",
  },
  ["edn"] = {
    icon = get("file-code"),
    color = "#519aba",
    cterm_color = "67",
    name = "Edn",
  },
  ["eex"] = {
    icon = get("elixir"),
    color = "#a074c4",
    cterm_color = "140",
    name = "Eex",
  },
  ["ejs"] = {
    icon = get("file-code"),
    color = "#cbcb41",
    cterm_color = "185",
    name = "Ejs",
  },
  ["elm"] = {
    icon = get("elm"),
    color = "#519aba",
    cterm_color = "67",
    name = "Elm",
  },
  ["epp"] = {
    icon = get("project"),
    color = "#FFA61A",
    name = "Epp",
  },
  ["erb"] = {
    icon = get("file-code"),
    color = "#701516",
    cterm_color = "52",
    name = "Erb",
  },
  ["erl"] = {
    icon = get("file-code"),
    color = "#B83998",
    cterm_color = "132",
    name = "Erl",
  },
  ["ex"] = {
    icon = get("elixir"),
    color = "#a074c4",
    cterm_color = "140",
    name = "Ex",
  },
  ["exs"] = {
    icon = get("elixir"),
    color = "#a074c4",
    cterm_color = "140",
    name = "Exs",
  },
  ["f#"] = {
    icon = get("diamond"),
    color = "#519aba",
    cterm_color = "67",
    name = "Fsharp",
  },
  ["favicon.ico"] = {
    icon = get("star"),
    color = "#cbcb41",
    cterm_color = "185",
    name = "Favicon",
  },
  ["fish"] = {
    icon = get("terminal"),
    color = "#4d5a5e",
    cterm_color = "59",
    name = "Fish",
  },
  ["fs"] = {
    icon = get("diamond"),
    color = "#519aba",
    cterm_color = "67",
    name = "Fs",
  },
  ["fsi"] = {
    icon = get("diamond"),
    color = "#519aba",
    cterm_color = "67",
    name = "Fsi",
  },
  ["fsscript"] = {
    icon = get("diamond"),
    color = "#519aba",
    cterm_color = "67",
    name = "Fsscript",
  },
  ["fsx"] = {
    icon = get("diamond"),
    color = "#519aba",
    cterm_color = "67",
    name = "Fsx",
  },
  ["gd"] = {
    icon = get("gear"),
    color = "#6d8086",
    cterm_color = "66",
    name = "GDScript",
  },
  ["gemspec"] = {
    icon = get("ruby"),
    color = "#701516",
    cterm_color = "52",
    name = "Gemspec",
  },
  ["gif"] = {
    icon = get("image"),
    color = "#a074c4",
    cterm_color = "140",
    name = "Gif",
  },
  ["git"] = {
    icon = get("git-commit"),
    color = "#F14C28",
    cterm_color = "202",
    name = "GitLogo",
  },
  ["glb"] = {
    icon = get("file-binary"),
    color = "#FFB13B",
    cterm_color = "215",
    name = "BinaryGLTF",
  },
  ["go"] = {
    icon = get("go"),
    color = "#519aba",
    cterm_color = "67",
    name = "Go",
  },
  ["godot"] = {
    icon = get("file-code"),
    color = "#6d8086",
    cterm_color = "66",
    name = "GodotProject",
  },
  ["gruntfile"] = {
    icon = get("javascript"),
    color = "#e37933",
    cterm_color = "173",
    name = "Gruntfile",
  },
  ["gulpfile"] = {
    icon = get("file-code"),
    color = "#cc3e44",
    cterm_color = "167",
    name = "Gulpfile",
  },
  ["h"] = {
    icon = get("file-code"),
    color = "#a074c4",
    cterm_color = "140",
    name = "H",
  },
  ["haml"] = {
    icon = get("file-code"),
    color = "#eaeae1",
    cterm_color = "188",
    name = "Haml",
  },
  ["hbs"] = {
    icon = get("file-code"),
    color = "#f0772b",
    cterm_color = "208",
    name = "Hbs",
  },
  ["heex"] = {
    icon = get("elixir"),
    color = "#a074c4",
    cterm_color = "140",
    name = "Heex",
  },
  ["hh"] = {
    icon = get("file-code"),
    color = "#a074c4",
    cterm_color = "140",
    name = "Hh",
  },
  ["hpp"] = {
    icon = get("file-code"),
    color = "#a074c4",
    cterm_color = "140",
    name = "Hpp",
  },
  ["hrl"] = {
    icon = get("file-code"),
    color = "#B83998",
    cterm_color = "132",
    name = "Hrl",
  },
  ["hs"] = {
    icon = get("file-code"),
    color = "#a074c4",
    cterm_color = "140",
    name = "Hs",
  },
  ["htm"] = {
    icon = get("file-code"),
    color = "#e34c26",
    cterm_color = "166",
    name = "Htm",
  },
  ["html"] = {
    icon = get("file-code"),
    color = "#e34c26",
    cterm_color = "166",
    name = "Html",
  },
  ["hxx"] = {
    icon = get("file-code"),
    color = "#a074c4",
    cterm_color = "140",
    name = "Hxx",
  },
  ["ico"] = {
    icon = get("image"),
    color = "#cbcb41",
    cterm_color = "185",
    name = "Ico",
  },
  ["import"] = {
    icon = get("package-dependencies"),
    color = "#ECECEC",
    cterm_color = "231",
    name = "ImportConfiguration",
  },
  ["ini"] = {
    icon = get("gear"),
    color = "#6d8086",
    cterm_color = "66",
    name = "Ini",
  },
  ["java"] = {
    icon = get("java"),
    color = "#cc3e44",
    cterm_color = "167",
    name = "Java",
  },
  ["jl"] = {
    icon = get("file-code"),
    color = "#a270ba",
    cterm_color = "133",
    name = "Jl",
  },
  ["jpeg"] = {
    icon = get("image"),
    color = "#a074c4",
    cterm_color = "140",
    name = "Jpeg",
  },
  ["jpg"] = {
    icon = get("image"),
    color = "#a074c4",
    cterm_color = "140",
    name = "Jpg",
  },
  ["js"] = {
    icon = get("javascript"),
    color = "#cbcb41",
    cterm_color = "185",
    name = "Js",
  },
  ["json"] = {
    icon = get("json"),
    color = "#cbcb41",
    cterm_color = "185",
    name = "Json",
  },
  ["jsx"] = {
    icon = get("react"),
    color = "#519aba",
    cterm_color = "67",
    name = "Jsx",
  },
  ["ksh"] = {
    icon = get("terminal"),
    color = "#4d5a5e",
    cterm_color = "59",
    name = "Ksh",
  },
  ["kt"] = {
    icon = get("kotlin"),
    color = "#F88A02",
    cterm_color = "208",
    name = "Kotlin",
  },
  ["leex"] = {
    icon = get("elixir"),
    color = "#a074c4",
    cterm_color = "140",
    name = "Leex",
  },
  ["less"] = {
    icon = get("css"),
    color = "#563d7c",
    cterm_color = "60",
    name = "Less",
  },
  ["lhs"] = {
    icon = get("file-code"),
    color = "#a074c4",
    cterm_color = "140",
    name = "Lhs",
  },
  ["license"] = {
    icon = get("file-badge"),
    color = "#cbcb41",
    cterm_color = "185",
    name = "License",
  },
  ["lua"] = {
    icon = get("lua"),
    color = "#51a0cf",
    cterm_color = "74",
    name = "Lua",
  },
  ["makefile"] = {
    icon = get("gear"),
    color = "#6d8086",
    cterm_color = "66",
    name = "Makefile",
  },
  ["markdown"] = {
    icon = get("markdown"),
    color = "#519aba",
    cterm_color = "67",
    name = "Markdown",
  },
  ["material"] = {
    icon = get("browser"),
    color = "#B83998",
    cterm_color = "132",
    name = "Material",
  },
  ["md"] = {
    icon = get("markdown"),
    color = "#519aba",
    cterm_color = "67",
    name = "Md",
  },
  ["mdx"] = {
    icon = get("markdown"),
    color = "#519aba",
    cterm_color = "67",
    name = "Mdx",
  },
  ["mint"] = {
    icon = get("desktop-download"),
    color = "#87c095",
    cterm_color = "108",
    name = "Mint",
  },
  ["mix.lock"] = {
    icon = get("elixir"),
    color = "#a074c4",
    cterm_color = "140",
    name = "MixLock",
  },
  ["mjs"] = {
    icon = get("javascript"),
    color = "#f1e05a",
    cterm_color = "221",
    name = "Mjs",
  },
  ["ml"] = {
    icon = get("file-code"),
    color = "#e37933",
    cterm_color = "173",
    name = "Ml",
  },
  ["mli"] = {
    icon = get("file-code"),
    color = "#e37933",
    cterm_color = "173",
    name = "Mli",
  },
  ["mustache"] = {
    icon = get("file-code"),
    color = "#e37933",
    cterm_color = "173",
    name = "Mustache",
  },
  ["nim"] = {
    icon = get("file-code"),
    color = "#f3d400",
    cterm_color = "220",
    name = "Nim",
  },
  ["nix"] = {
    icon = get("file-code"),
    color = "#7ebae4",
    cterm_color = "110",
    name = "Nix",
  },
  ["node_modules"] = {
    icon = get("node"),
    color = "#E8274B",
    cterm_color = "161",
    name = "NodeModules",
  },
  ["opus"] = {
    icon = get("file-binary"),
    color = "#F88A02",
    cterm_color = "208",
    name = "OPUS",
  },
  ["otf"] = {
    icon = get("typography"),
    color = "#ECECEC",
    cterm_color = "231",
    name = "OpenTypeFont",
  },
  ["pck"] = {
    icon = get("package"),
    color = "#6d8086",
    cterm_color = "66",
    name = "PackedResource",
  },
  ["pdf"] = {
    icon = get("file"),
    color = "#b30b00",
    cterm_color = "124",
    name = "Pdf",
  },
  ["php"] = {
    icon = get("php"),
    color = "#a074c4",
    cterm_color = "140",
    name = "Php",
  },
  ["pl"] = {
    icon = get("perl"),
    color = "#519aba",
    cterm_color = "67",
    name = "Pl",
  },
  ["pm"] = {
    icon = get("perl"),
    color = "#519aba",
    cterm_color = "67",
    name = "Pm",
  },
  ["png"] = {
    icon = get("image"),
    color = "#a074c4",
    cterm_color = "140",
    name = "Png",
  },
  ["pp"] = {
    icon = get("project"),
    color = "#FFA61A",
    name = "Pp",
  },
  ["ppt"] = {
    icon = get("file"),
    color = "#cb4a32",
    cterm_color = "167",
    name = "Ppt",
  },
  ["pro"] = {
    icon = get("file-code"),
    color = "#e4b854",
    cterm_color = "179",
    name = "Prolog",
  },
  ["procfile"] = {
    icon = get("file-code"),
    color = "#a074c4",
    cterm_color = "140",
    name = "Procfile",
  },
  ["ps1"] = {
    icon = get("terminal"),
    color = "#4d5a5e",
    cterm_color = "59",
    name = "PromptPs1",
  },
  ["psb"] = {
    icon = get("image"),
    color = "#519aba",
    cterm_color = "67",
    name = "Psb",
  },
  ["psd"] = {
    icon = get("image"),
    color = "#519aba",
    cterm_color = "67",
    name = "Psd",
  },
  ["py"] = {
    icon = get("python"),
    color = "#ffbc03",
    cterm_color = "61",
    name = "Py",
  },
  ["pyc"] = {
    icon = get("python"),
    color = "#ffe291",
    cterm_color = "67",
    name = "Pyc",
  },
  ["pyd"] = {
    icon = get("python"),
    color = "#ffe291",
    cterm_color = "67",
    name = "Pyd",
  },
  ["pyo"] = {
    icon = get("python"),
    color = "#ffe291",
    cterm_color = "67",
    name = "Pyo",
  },
  ["r"] = {
    icon = get("r"),
    color = "#358a5b",
    cterm_color = "65",
    name = "R",
  },
  ["rake"] = {
    icon = get("ruby"),
    color = "#701516",
    cterm_color = "52",
    name = "Rake",
  },
  ["rakefile"] = {
    icon = get("ruby"),
    color = "#701516",
    cterm_color = "52",
    name = "Rakefile",
  },
  ["rb"] = {
    icon = get("ruby"),
    color = "#701516",
    cterm_color = "52",
    name = "Rb",
  },
  ["rlib"] = {
    icon = get("rust"),
    color = "#dea584",
    cterm_color = "180",
    name = "Rlib",
  },
  ["rmd"] = {
    icon = get("markdown"),
    color = "#519aba",
    cterm_color = "67",
    name = "Rmd",
  },
  ["rproj"] = {
    icon = get("r"),
    color = "#358a5b",
    cterm_color = "65",
    name = "Rproj",
  },
  ["rs"] = {
    icon = get("rust"),
    color = "#dea584",
    cterm_color = "180",
    name = "Rs",
  },
  ["rss"] = {
    icon = get("rss"),
    color = "#FB9D3B",
    cterm_color = "215",
    name = "Rss",
  },
  ["sass"] = {
    icon = get("css"),
    color = "#f55385",
    cterm_color = "204",
    name = "Sass",
  },
  ["scala"] = {
    icon = get("scala"),
    color = "#cc3e44",
    cterm_color = "167",
    name = "Scala",
  },
  ["scss"] = {
    icon = get("css"),
    color = "#f55385",
    cterm_color = "204",
    name = "Scss",
  },
  ["sh"] = {
    icon = get("terminal"),
    color = "#4d5a5e",
    cterm_color = "59",
    name = "Sh",
  },
  ["sig"] = {
    icon = get("file-code"),
    color = "#e37933",
    cterm_color = "173",
    name = "Sig",
  },
  ["slim"] = {
    icon = get("file-code"),
    color = "#e34c26",
    cterm_color = "166",
    name = "Slim",
  },
  ["sln"] = {
    icon = get("vscode"),
    color = "#854CC7",
    cterm_color = "98",
    name = "Sln",
  },
  ["sml"] = {
    icon = get("file-code"),
    color = "#e37933",
    cterm_color = "173",
    name = "Sml",
  },
  ["sql"] = {
    icon = get("database"),
    color = "#dad8d8",
    cterm_color = "188",
    name = "Sql",
  },
  ["sqlite"] = {
    icon = get("database"),
    color = "#dad8d8",
    cterm_color = "188",
    name = "Sql",
  },
  ["sqlite3"] = {
    icon = get("database"),
    color = "#dad8d8",
    cterm_color = "188",
    name = "Sql",
  },
  ["styl"] = {
    icon = get("css"),
    color = "#8dc149",
    cterm_color = "107",
    name = "Styl",
  },
  ["sublime"] = {
    icon = get("json"),
    color = "#e37933",
    cterm_color = "98",
    name = "Suo",
  },
  ["suo"] = {
    icon = get("vscode"),
    color = "#854CC7",
    cterm_color = "98",
    name = "Suo",
  },
  ["svelte"] = {
    icon = get("svelte"),
    color = "#ff3e00",
    cterm_color = "202",
    name = "Svelte",
  },
  ["svg"] = {
    icon = get("north-star"),
    color = "#FFB13B",
    cterm_color = "215",
    name = "Svg",
  },
  ["swift"] = {
    icon = get("swift"),
    color = "#e37933",
    cterm_color = "173",
    name = "Swift",
  },
  ["t"] = {
    icon = get("perl"),
    color = "#519aba",
    cterm_color = "67",
    name = "Tor",
  },
  ["terminal"] = {
    icon = get("terminal"),
    color = "#31B53E",
    cterm_color = "71",
    name = "Terminal",
  },
  ["tex"] = {
    icon = get("file-code"),
    color = "#3D6117",
    cterm_color = "58",
    name = "Tex",
  },
  ["toml"] = {
    icon = get("file-code"),
    color = "#6d8086",
    cterm_color = "66",
    name = "Toml",
  },
  ["tres"] = {
    icon = get("database"),
    color = "#cbcb41",
    cterm_color = "185",
    name = "TextResource",
  },
  ["ts"] = {
    icon = get("typescript"),
    color = "#519aba",
    cterm_color = "67",
    name = "Ts",
  },
  ["tscn"] = {
    icon = get("file-code"),
    color = "#a074c4",
    cterm_color = "140",
    name = "TextScene",
  },
  ["tsx"] = {
    icon = get("react"),
    color = "#519aba",
    cterm_color = "67",
    name = "Tsx",
  },
  ["twig"] = {
    icon = get("file-code"),
    color = "#8dc149",
    cterm_color = "107",
    name = "Twig",
  },
  ["txt"] = {
    icon = get("file"),
    color = "#89e051",
    cterm_color = "113",
    name = "Txt",
  },
  ["vim"] = {
    icon = get("vim"),
    color = "#019833",
    cterm_color = "29",
    name = "Vim",
  },
  ["vue"] = {
    icon = get("vue"),
    color = "#8dc149",
    cterm_color = "107",
    name = "Vue",
  },
  ["webmanifest"] = {
    icon = get("json"),
    color = "#f1e05a",
    cterm_color = "221",
    name = "Webmanifest",
  },
  ["webp"] = {
    icon = get("image"),
    color = "#a074c4",
    cterm_color = "140",
    name = "Webp",
  },
  ["webpack"] = {
    icon = get("package"),
    color = "#519aba",
    cterm_color = "67",
    name = "Webpack",
  },
  ["xcplayground"] = {
    icon = get("swift"),
    color = "#e37933",
    cterm_color = "173",
    name = "XcPlayground",
  },
  ["xls"] = {
    icon = get("file"),
    color = "#207245",
    cterm_color = "23",
    name = "Xls",
  },
  ["xml"] = {
    icon = get("file-code"),
    color = "#e37933",
    cterm_color = "173",
    name = "Xml",
  },
  ["xul"] = {
    icon = get("browser"),
    color = "#e37933",
    cterm_color = "173",
    name = "Xul",
  },
  ["yaml"] = {
    icon = get("yaml"),
    color = "#6d8086",
    cterm_color = "66",
    name = "Yaml",
  },
  ["yml"] = {
    icon = get("yaml"),
    color = "#6d8086",
    cterm_color = "66",
    name = "Yml",
  },
  ["zig"] = {
    icon = get("zap"),
    color = "#f69a1b",
    cterm_color = "208",
    name = "Zig",
  },
  ["zsh"] = {
    icon = get("terminal"),
    color = "#89e051",
    cterm_color = "113",
    name = "Zsh",
  },
})

devicons.set_default_icon(get("file"), "#6d8086")
